import { Pencil, Plus, Save, Trash2, X } from "lucide-react";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { useState, type FormEvent } from "react";
import { toast } from "sonner";
import { api, unwrap } from "../api/client";
import { useDialog } from "../components/DialogSystem";
import type { FAQ } from "./LegalPages";

export function AdminFAQPage() {
  const qc = useQueryClient(); const dialog = useDialog(); const [editing, setEditing] = useState<FAQ | null>(); const { data = [], isLoading } = useQuery({ queryKey: ["admin-faqs"], queryFn: () => api.get("/admin/faqs").then(unwrap<FAQ[]>) }); const refresh = () => qc.invalidateQueries({ queryKey: ["admin-faqs"] });
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); const input = { question: form.get("question"), answer: form.get("answer"), displayOrder: Number(form.get("displayOrder")), isActive: form.get("isActive") === "on" }; if (editing?.id) await api.patch(`/admin/faqs/${editing.id}`, input); else await api.post("/admin/faqs", input); toast.success(editing?.id ? "FAQ updated" : "FAQ added"); setEditing(undefined); await refresh(); void qc.invalidateQueries({ queryKey: ["faqs"] }); }
  async function remove(item: FAQ) { if (!await dialog.confirm({ title: "Delete FAQ?", message: `Delete “${item.question}”?`, confirmLabel: "Delete", dangerous: true })) return; await api.delete(`/admin/faqs/${item.id}`); toast.success("FAQ deleted"); await refresh(); void qc.invalidateQueries({ queryKey: ["faqs"] }); }
  return <div className="admin-page"><header><div><p className="eyebrow">HELP CENTRE</p><h1>FAQ Management</h1></div><button className="button primary" onClick={() => setEditing(null)}><Plus/> Add FAQ</button></header>{editing !== undefined && <form className="faq-editor" onSubmit={submit}><header><h2>{editing ? "Edit FAQ" : "Add FAQ"}</h2><button type="button" onClick={() => setEditing(undefined)} aria-label="Close"><X/></button></header><label>Question<input name="question" defaultValue={editing?.question} required maxLength={500}/></label><label>Answer<textarea name="answer" rows={6} defaultValue={editing?.answer} required maxLength={10000}/></label><label>Display order<input name="displayOrder" type="number" min="0" defaultValue={editing?.displayOrder ?? data.length + 1}/></label><label className="check-line"><input name="isActive" type="checkbox" defaultChecked={editing?.isActive ?? true}/> Published on website</label><button className="button primary"><Save/> Save FAQ</button></form>}{isLoading ? <p>Loading FAQs…</p> : <div className="admin-faq-list">{data.map((item) => <article key={item.id}><span>{item.displayOrder}</span><div><h2>{item.question}</h2><p>{item.answer}</p><small>{item.isActive ? "Published" : "Disabled"}</small></div><div><button onClick={() => setEditing(item)} aria-label={`Edit ${item.question}`}><Pencil/></button><button onClick={() => remove(item)} aria-label={`Delete ${item.question}`}><Trash2/></button></div></article>)}</div>}</div>;
}
