import { zodResolver } from "@hookform/resolvers/zod";
import { useQuery } from "@tanstack/react-query";
import { ArrowRight, Check, MessageCircle, X } from "lucide-react";
import { useState } from "react";
import { useForm } from "react-hook-form";
import { z } from "zod";
import { api, unwrap } from "../api/client";
import { formatINR } from "../services/whatsapp";
import { deliveryImageUrl, imageSrcSet } from "../services/images";
import type { Product, Settings } from "../types";

const quoteSchema = z.object({ productId: z.number().positive(), quantity: z.number().positive(), unit: z.string().min(1), customerName: z.string().min(2), phone: z.string().min(8), email: z.string().email().or(z.literal("")), city: z.string().min(2), requiredDeliveryDate: z.string().min(1), customisationRequired: z.boolean(), customisationDetails: z.string().optional(), budget: z.number().positive().optional(), message: z.string().min(10), website: z.string().max(0).optional() });
type QuoteInput = z.infer<typeof quoteSchema>;
type QuoteResult = { inquiryNumber: string; emailNotificationSent: boolean; whatsappUrl: string };

const customisationLabels: Array<[keyof Product, string]> = [["customBrandingAvailable", "Brand Logo"], ["customPackagingAvailable", "Custom Packaging"], ["customFragranceAvailable", "Fragrance Selection"], ["customColourAvailable", "Colour Selection"], ["giftMessageAvailable", "Gift Message"], ["eventBrandingAvailable", "Event Branding"], ["ribbonTagsAvailable", "Ribbon & Tags"]];

export function BulkOrdersPage() {
  const { data: products = [], isLoading } = useQuery({ queryKey: ["bulk-products"], queryFn: () => api.get("/bulk-products").then(unwrap<Product[]>) });
  const { data: settings } = useQuery({ queryKey: ["settings"], queryFn: () => api.get("/settings/public").then(unwrap<Settings>) });
  const [selected, setSelected] = useState<Product>(); const [result, setResult] = useState<QuoteResult>();
  const { register, handleSubmit, reset, setValue, formState: { errors, isSubmitting } } = useForm<QuoteInput>({ resolver: zodResolver(quoteSchema), defaultValues: { email: "", customisationRequired: false, message: "Please share pricing, production timeline and available customisation options.", website: "" } });
  const selectProduct = (product: Product) => { setSelected(product); setResult(undefined); setValue("productId", product.id); setValue("quantity", product.bulkMOQ ?? 1); setValue("unit", product.bulkUnit ?? "Pieces"); };
  const submit = async (input: QuoteInput) => { const whatsappWindow = window.open("about:blank", "_blank"); if (whatsappWindow) whatsappWindow.opener = null; try { const response = await api.post("/bulk-inquiries", { ...input, budget: input.budget || undefined }); setResult(response.data.data); reset(); if (whatsappWindow) whatsappWindow.location.href = response.data.data.whatsappUrl; } catch (error) { whatsappWindow?.close(); throw error; } };
  const genericWhatsApp = `https://wa.me/${settings?.whatsappNumber ?? "918421869308"}?text=${encodeURIComponent("Hello DIVA Candles,\nI would like to know more about your premium bulk candle collection.")}`;
  return <><section className="bulk-hero"><div><p className="eyebrow">BULK ORDERS</p><h1>Premium Bulk<br/><em>Candle Collection</em></h1><p>Whether you’re planning a wedding, corporate event, festive celebration or a special gathering, DIVA offers handcrafted premium candles at exclusive bulk prices.</p><div className="button-row"><a href="#bulk-collection" className="button cream">Explore collection <ArrowRight/></a><a href={genericWhatsApp} target="_blank" rel="noopener noreferrer" className="button bulk-whatsapp"><MessageCircle/> WhatsApp us</a></div><small>Minimum order quantity varies by product.</small></div><div className="bulk-hero-art bulk-hero-photo"><img src="/diva-celebration.png" alt="Premium DIVA candle arrangement for celebrations and bulk gifting"/></div></section>
    <section className="section bulk-products" id="bulk-collection"><div className="section-heading"><div><p className="eyebrow">CRAFTED FOR YOUR OCCASION</p><h2>Choose your <em>collection</em></h2></div></div>{isLoading ? <p>Preparing the collection…</p> : <div className="bulk-grid">{products.map((product) => { const image = product.images.find((item) => item.isPrimary) ?? product.images[0]; const options = customisationLabels.filter(([key]) => Boolean(product[key])); return <article className="bulk-card" key={product.id}><div className="bulk-image">{image ? <img src={deliveryImageUrl(image.imageUrl, 400)} srcSet={imageSrcSet(image.imageUrl)} sizes="(max-width: 768px) 50vw, 25vw" alt={image.altText} loading="lazy"/> : <div className="image-fallback"><b>DIVA CANDLES</b><span>Image Coming Soon</span></div>}</div><div className="bulk-card-copy"><p className="eyebrow">{product.category.name}</p><h3>{product.name}</h3><p>{product.bulkDescription || product.shortDescription}</p><div className="bulk-meta"><strong>MOQ: {product.bulkMOQ ?? "Custom"} {product.bulkUnit}</strong><span>{product.bulkPriceVisible && product.bulkStartingPrice ? `Starting ${formatINR(product.bulkStartingPrice)}` : "Request Price"}</span></div>{options.length > 0 && <div className="option-chips">{options.slice(0, 4).map(([, label]) => <span key={label}>{label}</span>)}</div>}<div className="bulk-actions"><button onClick={() => selectProduct(product)}>Request quote</button>{product.whatsappAvailable && <a href={genericWhatsApp} target="_blank" rel="noopener noreferrer"><MessageCircle/> WhatsApp</a>}</div></div></article>; })}</div>}</section>
    <section className="perfect-for"><p className="eyebrow">PERFECT FOR</p><h2>Made for meaningful scale.</h2><div>{["Corporate Events", "Wedding Favours", "Celebrations", "Hotels & Resorts", "Cafés", "Festivals", "Brand Launches", "Luxury Events"].map((item, index) => <article key={item}><span>0{index + 1}</span><h3>{item}</h3></article>)}</div></section>
    <section className="how-it-works"><p className="eyebrow">A SIMPLE, PERSONAL PROCESS</p><h2>How it works</h2><div>{[["Choose Your Product", "Browse our bulk collection."], ["Select Quantity", "Choose the quantity based on your requirement."], ["Request a Quote", "We share pricing and customisation options."], ["Production", "Each candle is handcrafted with premium materials."], ["Delivery", "Delivered safely across India."]].map(([title, copy], index) => <article key={title}><b>{index + 1}</b><h3>{title}</h3><p>{copy}</p></article>)}</div></section>
    {selected && <div className="quote-overlay" role="dialog" aria-modal="true" aria-labelledby="quote-title"><div className="quote-modal"><button className="quote-close" onClick={() => setSelected(undefined)} aria-label="Close quote form"><X/></button>{result ? <div className="quote-success"><Check/><p className="eyebrow">REQUEST RECEIVED</p><h2>Thank you.</h2><p>Your inquiry number is <strong>{result.inquiryNumber}</strong>. Our team will contact you shortly.</p><a className="button whatsapp" href={result.whatsappUrl} target="_blank" rel="noopener noreferrer"><MessageCircle/> Continue on WhatsApp</a></div> : <><p className="eyebrow">REQUEST A BULK QUOTE</p><h2 id="quote-title">{selected.name}</h2><p>Share your requirement and our team will prepare a considered quotation.</p><form onSubmit={handleSubmit(submit)}><input type="hidden" {...register("productId", { valueAsNumber: true })}/><div className="form-grid"><label>Quantity<input type="number" min={selected.bulkMOQ ?? 1} {...register("quantity", { valueAsNumber: true })}/><small>{errors.quantity?.message}</small></label><label>Unit<input {...register("unit")} readOnly/></label><label>Customer name<input {...register("customerName")}/><small>{errors.customerName?.message}</small></label><label>Mobile number<input {...register("phone")}/><small>{errors.phone?.message}</small></label><label>Email<input type="email" {...register("email")}/><small>{errors.email?.message}</small></label><label>City<input {...register("city")}/><small>{errors.city?.message}</small></label><label>Required delivery date<input type="date" min={new Date().toISOString().slice(0, 10)} {...register("requiredDeliveryDate")}/></label><label>Budget (optional)<input type="number" {...register("budget", { setValueAs: (value) => value === "" ? undefined : Number(value) })}/></label><label className="full quote-check"><input type="checkbox" {...register("customisationRequired")}/> Customisation required</label><label className="full">Customisation details<textarea rows={3} {...register("customisationDetails")}/></label><label className="full">Message<textarea rows={4} {...register("message")}/><small>{errors.message?.message}</small></label><label className="honeypot">Website<input {...register("website")}/></label></div><button className="button primary" disabled={isSubmitting}>{isSubmitting ? "Sending…" : "Submit quote request"}<ArrowRight/></button></form></>}</div></div>}
  </>;
}
