import { Link } from "react-router-dom";
import { useQuery } from "@tanstack/react-query";
import { ArrowRight, UserRound } from "lucide-react";
import { api, unwrap } from "../api/client";
import type { TeamMember } from "../types";

function TeamCards({ limit }: { limit?: number }) {
  const { data = [], isLoading } = useQuery({ queryKey: ["team"], queryFn: () => api.get("/team").then(unwrap<TeamMember[]>) });
  if (isLoading) return <p className="team-loading">Introducing our team…</p>;
  return <div className="team-grid">{data.slice(0, limit).map((member) => <article className={member.isFounder ? "founder" : ""} key={member.id}><div className="team-photo">{member.profileImageUrl ? <img src={member.profileImageUrl} alt={member.name} loading="lazy"/> : <UserRound/>}</div><div><p className="eyebrow">{member.isFounder ? "FOUNDER" : "CORE TEAM"}</p><h3>{member.name}</h3><strong>{member.designation}</strong><p>{member.description}</p></div></article>)}</div>;
}

export function AboutPage() { return <>
  <section className="page-hero dark"><p className="eyebrow">ABOUT DIVA CANDLES</p><h1>Luxury lives<br/>in the <em>details.</em></h1><p>At DIVA Candles, we believe true luxury is found in the soft glow of candlelight, the elegance of handcrafted artistry and the emotions that transform a house into a home.</p></section>
  <section className="editorial about-intro"><div><p className="eyebrow">BEAUTY WITH PURPOSE</p><h2>A soft glow.<br/>A lasting feeling.</h2><figure className="about-editorial-photo"><img src="/diva-hero-candles.png" alt="DIVA's refined handcrafted candle collection" loading="lazy"/><figcaption>Thoughtfully composed. Beautifully made.</figcaption></figure></div><div className="about-prose"><p>Founded with a passion for exceptional craftsmanship, DIVA Candles is a premium candle brand dedicated to creating luxurious handcrafted candles that inspire warmth, beauty and unforgettable experiences. Every creation thoughtfully blends timeless aesthetics with modern elegance, making each candle a statement of sophistication.</p><p>Using carefully selected wax, premium fragrances and artisan techniques, we craft candles that are more than décor—they are expressions of style, celebration and emotion. From intimate evenings and festive celebrations to beautifully styled homes, DIVA Candles elevates every moment with elegance.</p><p>Every collection reflects our commitment to quality, creativity and excellence. We do not simply create candles—we create experiences that leave a lasting impression.</p></div></section>
  <section className="brand-story"><div><p className="eyebrow">OUR BRAND STORY</p><h2>Every great brand<br/>begins with a <em>dream.</em></h2></div><div><p>DIVA Candles was born from a vision to redefine candles as luxurious lifestyle pieces rather than everyday essentials. Inspired by art, celebrations and timeless elegance, we set out to create handcrafted designs that capture emotions, preserve memories and bring warmth into every space.</p><p>What began as a passion for creating beautiful candles has grown into a brand that values authenticity, craftsmanship and meaningful connections. Every candle reflects countless hours of creativity, precision and dedication to delivering something truly special.</p><p>Today, DIVA Candles continues to create collections that celebrate life’s precious moments while bringing luxury into everyday living.</p></div></section>
  <section className="mission"><div><p className="eyebrow">OUR MISSION</p><h2>To craft premium handcrafted candles that inspire warmth, joy and connection.</h2><p>We combine exceptional quality, elegant design and memorable fragrances to create beautiful experiences.</p></div><div><p className="eyebrow">OUR VISION</p><h3>Homes and hearts illuminated around the world.</h3><p>To become one of the most admired luxury handcrafted candle brands, recognised for timeless designs, uncompromising quality and memorable fragrance experiences.</p><Link to="/shop" className="button cream">Explore the collection</Link></div></section>
  <section className="values-section"><div className="section-heading"><div><p className="eyebrow">WHAT GUIDES US</p><h2>Our <em>values</em></h2></div></div><div className="value-grid expanded"><article><span>01</span><h3>Craftsmanship</h3><p>Every candle is carefully handcrafted with attention to detail and uncompromising quality.</p></article><article><span>02</span><h3>Elegance</h3><p>We create timeless designs that complement sophisticated lifestyles and beautiful interiors.</p></article><article><span>03</span><h3>Quality</h3><p>From premium materials to refined finishing, excellence is at the heart of everything we create.</p></article><article><span>04</span><h3>Creativity</h3><p>We continuously innovate with unique collections inspired by celebrations, culture and modern living.</p></article><article><span>05</span><h3>Meaningful Experiences</h3><p>Our candles create memories, celebrate milestones and make every occasion extraordinary.</p></article></div></section>
  <section className="why-diva"><div><p className="eyebrow">WHY CHOOSE DIVA CANDLES?</p><h2>Created for those who appreciate meaningful luxury.</h2></div><ul><li>Premium handcrafted candles made with exceptional attention to detail.</li><li>Elegant designs for beautiful, characterful homes.</li><li>Beautiful fragrances that create a warm, inviting atmosphere.</li><li>Exclusive festive and decorative collections inspired by timeless traditions.</li><li>Perfect for celebrations, home décor and special occasions.</li><li>A commitment to quality, artistry and customer satisfaction in every creation.</li></ul></section>
  <section className="brand-promise"><p className="eyebrow">OUR PROMISE</p><h2>Passion. Precision. Purpose.</h2><p>Every DIVA Candle is created with passion, precision and purpose. We promise uncompromising quality, refined craftsmanship and an experience that brings warmth, elegance and lasting memories into your life.</p><blockquote>Illuminate Moments. Inspire Memories.</blockquote><small>Because every celebration deserves a beautiful glow, and every space deserves a touch of luxury.</small></section>
  <section className="team-preview section"><div className="section-heading"><div><p className="eyebrow">THE PEOPLE BEHIND THE FLAME</p><h2>Meet the hearts<br/>behind <em>DIVA</em></h2></div><Link to="/about/team">Meet the complete team <ArrowRight/></Link></div><TeamCards limit={3}/></section>
  <section className="about-cta"><p className="eyebrow">DISCOVER THE COLLECTION</p><h2>Bring a beautiful glow into your story.</h2><Link className="button cream" to="/shop">Shop DIVA Candles</Link></section>
</>; }

export function TeamPage() { return <><section className="page-hero dark team-hero"><p className="eyebrow">OUR CORE TEAM</p><h1>Meet the Hearts<br/>Behind <em>DIVA</em></h1><p>At DIVA Candles, every candle tells a story of passion, craftsmanship and togetherness. Our core team transforms a shared vision into a growing premium handcrafted candle brand.</p></section><section className="section team-page"><TeamCards/></section><section className="team-closing"><p className="eyebrow">BUILT TOGETHER, CRAFTED WITH LOVE</p><h2>More than a business.<br/>A family-built brand.</h2><p>Every member contributes in their own way to create handcrafted candles that celebrate beauty, warmth and meaningful moments.</p><blockquote>Together, we don’t just create candles — we create experiences that light up lives.</blockquote></section></>; }

export function CarePage() { return <section className="prose-page"><p className="eyebrow">CANDLE CARE</p><h1>A beautiful burn,<br/>every time.</h1><div className="care-grid"><article><b>01</b><h2>Trim the wick</h2><p>Before each burn, trim the wick to approximately 5 mm. This encourages an even flame and reduces soot.</p></article><article><b>02</b><h2>Create the first pool</h2><p>Let the wax melt close to the edge on the first burn. It helps prevent tunnelling on future burns.</p></article><article><b>03</b><h2>Burn mindfully</h2><p>Keep away from drafts and never burn unattended. Limit each session to the maker’s recommended time.</p></article><article><b>04</b><h2>Know when to stop</h2><p>Discontinue use when about 10 mm of wax remains. Protect delicate surfaces from heat.</p></article></div></section>; }

export function FaqPage() { const faqs = [["Are all candles handmade?", "Yes. DIVA Candles are produced in considered batches and finished by hand."], ["Can I customise candles for an event?", "Yes. Use our custom order form with your colours, fragrance direction, quantity, budget and delivery date."], ["How do corporate orders work?", "Share your brief and quantity. Our team will contact you with suitable formats, timelines and pricing."], ["Can I order on WhatsApp?", "Yes. Add one or more products to your WhatsApp cart, then send the pre-filled order message."]]; return <section className="prose-page"><p className="eyebrow">QUESTIONS, ANSWERED</p><h1>Frequently asked.</h1><div className="faq-list">{faqs.map(([q, a]) => <details key={q}><summary>{q}</summary><p>{a}</p></details>)}</div></section>; }

export function PolicyPage({ title }: { title: string }) { return <section className="prose-page policy"><p className="eyebrow">BUSINESS POLICY</p><h1>{title}</h1><div className="review-note">This policy is a business-review placeholder. DIVA Candles should approve fulfilment timelines, eligibility, fees and legal language before launch.</div><h2>Overview</h2><p>We aim to communicate clearly and handle every request with care. Final terms vary by product type, customisation, destination and order value.</p><h2>Before placing an order</h2><p>Please confirm product availability, total price, dispatch estimate and delivery information with our team. Custom and bulk work may require separate written approval.</p><h2>Need help?</h2><p>Contact DIVA Candles at info.divacandles@gmail.com or through WhatsApp for the latest information.</p></section>; }
