import { zodResolver } from "@hookform/resolvers/zod";
import { Facebook, Instagram, Linkedin, Mail, MessageCircle, Phone, Send, Youtube } from "lucide-react";
import { useQuery } from "@tanstack/react-query";
import { useState } from "react";
import { useForm } from "react-hook-form";
import { z } from "zod";
import { api, unwrap } from "../api/client";
import { useDialog } from "../components/DialogSystem";
import type { Settings } from "../types";

const schema = z.object({ customerName: z.string().trim().min(2, "Enter at least 2 characters").max(100), phone: z.string().trim().refine((value) => { let digits = value.replace(/\D/g, ""); if (digits.startsWith("91") && digits.length === 12) digits = digits.slice(2); return /^[6-9]\d{9}$/.test(digits); }, "Enter a valid Indian mobile number"), email: z.string().trim().email("Enter a valid email").or(z.literal("")), message: z.string().trim().min(5, "Enter at least 5 characters").max(2000), website: z.string().max(0).optional() });
type ContactForm = z.infer<typeof schema>;

export function ContactPage() {
  const { data: settings } = useQuery({ queryKey: ["settings"], queryFn: () => api.get("/settings/public").then(unwrap<Settings>) }); const { show } = useDialog(); const [lastWhatsApp, setLastWhatsApp] = useState("");
  const { register, handleSubmit, reset, formState: { errors, isSubmitting }, setError } = useForm<ContactForm>({ resolver: zodResolver(schema), defaultValues: { email: "", website: "" } });
  async function submit(values: ContactForm) { try { const result = await api.post("/contact-inquiries", values).then(unwrap<{ inquiryNumber: string; whatsappUrl: string }>); setLastWhatsApp(result.whatsappUrl); reset(); show({ kind: "success", title: "Thank You!", confirmLabel: "Close", message: <><p>Your inquiry has been submitted successfully.</p><p>Inquiry Reference:<br/><strong>{result.inquiryNumber}</strong></p><p>Our team will contact you shortly.</p><a className="button whatsapp dialog-whatsapp" href={result.whatsappUrl} target="_blank" rel="noopener noreferrer"><MessageCircle/> Continue on WhatsApp</a></> }); } catch (error: any) { setError("root", { message: error.response?.data?.error?.message ?? "Your inquiry could not be submitted. Please try again." }); } }
  const socials = [{ url: settings?.instagramUrl, label: "Instagram", Icon: Instagram }, { url: settings?.facebookUrl, label: "Facebook", Icon: Facebook }, { url: settings?.youtubeUrl, label: "YouTube", Icon: Youtube }, { url: settings?.linkedinUrl, label: "LinkedIn", Icon: Linkedin }].filter((item) => item.url);
  return <><section className="contact-hero"><p className="eyebrow">WE WOULD LOVE TO HEAR FROM YOU</p><h1>Contact <em>DIVA Candles</em></h1><p>Share your question or candle requirement. Every message is saved with a reference number so our team can follow it thoughtfully.</p></section><section className="contact-layout"><aside><p className="eyebrow">DIVA CANDLES</p><h2>Let’s begin with a conversation.</h2><a href={`tel:${(settings?.phone ?? "+91 84218 69308").replace(/\s/g, "")}`}><Phone/> <span><small>Mobile</small>{settings?.phone ?? "+91 84218 69308"}</span></a><a href={`https://wa.me/${settings?.whatsappNumber ?? "918421869308"}`} target="_blank" rel="noopener noreferrer"><MessageCircle/> <span><small>WhatsApp</small>+91 84218 69308</span></a><a href={`mailto:${settings?.notificationEmail ?? "info.divacandles@gmail.com"}`}><Mail/> <span><small>Email</small>{settings?.notificationEmail ?? "info.divacandles@gmail.com"}</span></a>{socials.length > 0 && <div className="contact-socials">{socials.map(({ url, label, Icon }) => <a key={label} href={url!} target="_blank" rel="noopener noreferrer" aria-label={label}><Icon/></a>)}</div>}</aside><form onSubmit={handleSubmit(submit)}><p className="eyebrow">CONTACT DIVA CANDLES</p><h2>How may we help?</h2><label>Customer Name *<input {...register("customerName")} autoComplete="name"/><small>{errors.customerName?.message}</small></label><label>Mobile Number *<input {...register("phone")} inputMode="tel" autoComplete="tel" placeholder="+91 8421869308"/><small>{errors.phone?.message}</small></label><label>Email<input {...register("email")} type="email" autoComplete="email"/><small>{errors.email?.message}</small></label><label>Description / Message *<textarea {...register("message")} rows={6}/><small>{errors.message?.message}</small></label><label className="honeypot">Website<input {...register("website")} tabIndex={-1}/></label>{errors.root && <p className="form-error">{errors.root.message}</p>}<button className="button primary" disabled={isSubmitting}>{isSubmitting ? "Sending…" : "Send Inquiry"}<Send/></button>{lastWhatsApp && <a className="contact-repeat-whatsapp" href={lastWhatsApp} target="_blank" rel="noopener noreferrer">Continue previous inquiry on WhatsApp</a>}</form></section></>;
}
