import { ArrowRight, HandHeart, Leaf, Sparkles } from "lucide-react";
import { useQuery } from "@tanstack/react-query";
import { Link } from "react-router-dom";
import { api, unwrap } from "../api/client";
import { ProductCard } from "../components/ProductCard";
import { BrandVisualCarousel } from "../components/BrandVisualCarousel";
import { PeacockWritingText } from "../components/PeacockWritingText";
import type { Product } from "../types";

export function HomePage() {
  const { data: products = [], isLoading } = useQuery({ queryKey: ["products", "featured"], queryFn: () => api.get("/products/featured").then(unwrap<Product[]>) });
  const { data: bestSellers = [] } = useQuery({ queryKey: ["products", "best-sellers"], queryFn: () => api.get("/products/best-sellers").then(unwrap<Product[]>) });
  const { data: newArrivals = [] } = useQuery({ queryKey: ["products", "new-arrivals"], queryFn: () => api.get("/products/new-arrivals").then(unwrap<Product[]>) });
  const { data: festive } = useQuery({ queryKey: ["category", "festive-collection"], queryFn: () => api.get("/categories/festive-collection").then(unwrap<{ products: Product[] }>) });
  const { data: gifting } = useQuery({ queryKey: ["category", "gift-sets"], queryFn: () => api.get("/categories/gift-sets").then(unwrap<{ products: Product[] }>) });
  return <>
    <section className="hero hero-immersive"><div className="hero-stage"><BrandVisualCarousel/></div><div className="hero-copy"><p className="eyebrow">HANDCRAFTED IN INDIA · MADE FOR MEANINGFUL MOMENTS</p><h1 className="hero-title">DIVA<br/><em>Candles</em></h1><PeacockWritingText text="दीपज्योति: सुखप्रदा" duration={10000}/><p className="hero-quote">Flame that gives joy. Light that turns everyday spaces into unforgettable moments.</p><div className="button-row"><Link className="button primary" to="/shop">Explore the collection <ArrowRight size={17}/></Link><Link className="button ghost" to="/about">Our story</Link></div><div className="hero-note"><Sparkles size={18}/><span>Small-batch craft<br/><b>Illuminate Moments. Inspire Memories.</b></span></div></div></section>
    <section className="marquee"><span>HAND POURED</span><i>✦</i><span>PREMIUM FRAGRANCE</span><i>✦</i><span>SMALL BATCH</span><i>✦</i><span>TIMELESS DESIGN</span></section>
    <section className="section products-section"><div className="section-heading"><div><p className="eyebrow">CURATED FOR YOU</p><h2>Objects of <em>warmth</em></h2></div><Link to="/shop">View all candles <ArrowRight size={17}/></Link></div>{isLoading ? <div className="loading-grid">Loading the collection…</div> : <div className="product-grid">{products.map((product) => <ProductCard key={product.id} product={product}/>)}</div>}</section>
    {!!bestSellers.length && <section className="section products-section home-product-alt"><div className="section-heading"><div><p className="eyebrow">LOVED BY OUR COMMUNITY</p><h2>Best <em>sellers</em></h2></div><Link to="/shop">View all <ArrowRight size={17}/></Link></div><div className="product-grid">{bestSellers.slice(0, 8).map((product) => <ProductCard key={product.id} product={product}/>)}</div></section>}
    {!!newArrivals.length && <section className="section products-section"><div className="section-heading"><div><p className="eyebrow">NEWLY POURED</p><h2>New <em>arrivals</em></h2></div><Link to="/shop">View all <ArrowRight size={17}/></Link></div><div className="product-grid">{newArrivals.slice(0, 8).map((product) => <ProductCard key={product.id} product={product}/>)}</div></section>}
    {!!festive?.products.length && <section className="section products-section home-product-alt"><div className="section-heading"><div><p className="eyebrow">CELEBRATION READY</p><h2>Festive <em>collection</em></h2></div><Link to="/shop?category=festive-collection">View all <ArrowRight size={17}/></Link></div><div className="product-grid">{festive.products.slice(0, 8).map((product) => <ProductCard key={product.id} product={product}/>)}</div></section>}
    {!!gifting?.products.length && <section className="section products-section"><div className="section-heading"><div><p className="eyebrow">THOUGHTFULLY PRESENTED</p><h2>Gifting <em>collection</em></h2></div><Link to="/shop?category=gift-sets">View all <ArrowRight size={17}/></Link></div><div className="product-grid">{gifting.products.slice(0, 8).map((product) => <ProductCard key={product.id} product={product}/>)}</div></section>}
    <section className="story-split"><div className="story-art story-photo"><img src="/diva-artisan-story.png" alt="DIVA artisan hand-pouring a candle" loading="lazy"/><p>Every flame begins<br/>with a pair of hands.</p></div><div className="story-copy"><p className="eyebrow">ABOUT DIVA CANDLES</p><h2>Made slowly.<br/>Remembered <em>always.</em></h2><p>DIVA Candles was born from a vision to redefine candles as luxurious lifestyle pieces rather than everyday essentials. Inspired by art, celebrations and timeless elegance, every handcrafted design is created to capture emotions, preserve memories and bring warmth into every space.</p><Link to="/about" className="text-link">Discover our complete story <ArrowRight size={17}/></Link><div className="values"><span><HandHeart/>Handcrafted</span><span><Leaf/>Premium quality</span><span><Sparkles/>Memorable fragrance</span></div></div></section>
    <section className="home-purpose"><article><p className="eyebrow">OUR MISSION</p><h2>Craft beautiful experiences.</h2><p>To combine exceptional quality, elegant design and memorable fragrances in handcrafted candles that inspire warmth, joy and connection.</p></article><article><p className="eyebrow">OUR VISION</p><h2>Illuminate homes and hearts.</h2><p>To become one of the most admired luxury handcrafted candle brands, recognised for timeless designs, uncompromising quality and unforgettable fragrance experiences.</p></article></section>
    <section className="quote"><Sparkles/><blockquote>“Because every celebration deserves a beautiful glow, and every space deserves a touch of luxury.”</blockquote><p>— THE DIVA PROMISE</p></section>
  </>;
}
