import { ArrowRight, CheckCircle2, MessageCircle } from "lucide-react";
import { zodResolver } from "@hookform/resolvers/zod";
import { useForm } from "react-hook-form";
import { useState } from "react";
import { z } from "zod";
import { api } from "../api/client";

const inquiryTypes = ["GENERAL", "PRODUCT", "BULK_ORDER", "CORPORATE_GIFTING", "WEDDING", "CUSTOM_ORDER", "EVENT", "OTHER"] as const;
const schema = z.object({ inquiryType: z.enum(inquiryTypes), customerName: z.string().min(2, "Please enter your name"), phone: z.string().min(8, "Please enter a valid WhatsApp number"), email: z.string().email().or(z.literal("")), city: z.string().optional(), quantity: z.number().positive().optional(), occasion: z.string().optional(), preferredContactMethod: z.enum(["WHATSAPP", "EMAIL"]), message: z.string().min(10, "Tell us a little more"), website: z.string().max(0).optional() });
type FormData = z.infer<typeof schema>;
const labels: Record<FormData["inquiryType"], string> = { GENERAL: "General", PRODUCT: "Product", BULK_ORDER: "Bulk Order", CORPORATE_GIFTING: "Corporate Gifting", WEDDING: "Wedding", CUSTOM_ORDER: "Custom Candle", EVENT: "Event", OTHER: "Other" };

export function InquiryPage({ type = "GENERAL", title = "Let’s create something meaningful.", intro = "Tell us what you have in mind. We’ll respond with thoughtful options and next steps." }: { type?: string; title?: string; intro?: string }) {
  const validType = inquiryTypes.includes(type as FormData["inquiryType"]) ? type as FormData["inquiryType"] : "GENERAL";
  const { register, handleSubmit, formState: { errors, isSubmitting }, setError } = useForm<FormData>({ resolver: zodResolver(schema), defaultValues: { inquiryType: validType, preferredContactMethod: "WHATSAPP", email: "" } });
  const [result, setResult] = useState<string | null>(null);
  async function submit(data: FormData) { try { const response = await api.post("/inquiries", data); setResult(response.data.data.inquiryNumber); } catch { setError("root", { message: "We couldn’t submit this just now. Please try again or contact us on WhatsApp." }); } }
  if (result) { const text = encodeURIComponent(`Hello DIVA Candles, I have submitted inquiry ${result}. Please help me with the next steps.`); return <section className="success-page"><CheckCircle2/><p className="eyebrow">INQUIRY RECEIVED</p><h1>Thank you. We’ll be in touch.</h1><p>Your reference number is <strong>{result}</strong>. Keep it handy when you contact us.</p><a className="button whatsapp" href={`https://wa.me/918421869308?text=${text}`} target="_blank" rel="noreferrer"><MessageCircle/> Continue on WhatsApp</a></section>; }
  return <section className="inquiry-page"><div className="inquiry-intro"><p className="eyebrow">WHATSAPP & EMAIL SUPPORT</p><h1>{title}</h1><p>{intro}</p><blockquote>“Beautiful details make every celebration feel unmistakably personal.”</blockquote></div><form onSubmit={handleSubmit(submit)}><div className="form-grid"><label>Inquiry type<select {...register("inquiryType")}>{inquiryTypes.map((value) => <option key={value} value={value}>{labels[value]}</option>)}</select></label><label>Full name<input {...register("customerName")} placeholder="Your name"/><small>{errors.customerName?.message}</small></label><label>WhatsApp number<input {...register("phone")} placeholder="+91"/><small>{errors.phone?.message}</small></label><label>Email (optional)<input {...register("email")} type="email" placeholder="you@example.com"/><small>{errors.email?.message}</small></label><label>City<input {...register("city")} placeholder="Your city"/></label><label>Quantity<input {...register("quantity", { setValueAs: (value) => value === "" ? undefined : Number(value) })} type="number" placeholder="Approximate"/></label><label>Occasion<input {...register("occasion")} placeholder="Wedding, festival, celebration…"/></label><label>Preferred contact<select {...register("preferredContactMethod")}><option value="WHATSAPP">WhatsApp</option><option value="EMAIL">Email</option></select></label><label className="honeypot">Website<input {...register("website")} tabIndex={-1} autoComplete="off"/></label><label className="full">Tell us what you have in mind<textarea {...register("message")} rows={5} placeholder="Fragrance, colours, budget, date and any custom details…"/><small>{errors.message?.message}</small></label></div>{errors.root && <p className="form-error">{errors.root.message}</p>}<button className="button primary" disabled={isSubmitting}>{isSubmitting ? "Sending…" : "Send inquiry"}<ArrowRight size={17}/></button></form></section>;
}
